In [4]:
import pickle
with open('/home/hdd2/jo/nnUNet_preprocessed/Dataset218_AMOS2022_postChallenge_task1/nnUNetPlans_3d_fullres/amos_0405.pkl', 'rb') as f:
    data = pickle.load(f)

print(type(data))
print(data)  # if it's a dict

<class 'dict'>
{'nibabel_stuff': {'original_affine': array([[  -0.58854169,   -0.        ,    0.        ,  209.        ],
       [   0.        ,    0.58854169,    0.        , -395.41146851],
       [   0.        ,    0.        ,    5.        ,   58.99996948],
       [   0.        ,    0.        ,    0.        ,    1.        ]]), 'reoriented_affine': array([[   0.58854169,    0.        ,    0.        , -242.41147357],
       [   0.        ,    0.58854169,    0.        , -395.41146851],
       [   0.        ,    0.        ,    5.        ,   58.99996948],
       [   0.        ,    0.        ,    0.        ,    1.        ]])}, 'spacing': [5.0, 0.5885416865348816, 0.5885416865348816], 'shape_before_cropping': (90, 768, 768), 'bbox_used_for_cropping': [[0, 90], [0, 768], [0, 768]], 'shape_after_cropping_and_before_resampling': (90, 768, 768), 'class_locations': {1: array([[  0, 165, 263, 215],
       [  0, 198, 326, 215],
       [  0, 168, 296, 195],
       ...,
       [  0, 174, 274, 229],


In [16]:
import numpy as np

data = np.load('/home/hdd2/jo/nnUNet_preprocessed/Dataset218_AMOS2022_postChallenge_task1/nnUNetPlans_3d_fullres/amos_0408.npz')
print(data['data'])
print(data['data'].shape)
print("Shape:", data['data'].shape)
print("Data type:", data['data'].dtype)
print("Intensity range:", data['data'].min(), "to", data['data'].max())

# Example: get global mean/std if available
if 'mean' in data.files:
    print("Mean:", data['mean'])
if 'std' in data.files:
    print("Std:", data['std'])

[[[[-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   ...
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]]

  [[-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   ...
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]]

  [[-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   [-7.49413 -7.49413 -7.49413 ... -7.49413 -7.49413 -7.49413]
   ...
   [-7.49413 -7.49413 -7.49413

In [28]:
import nibabel as nib

img = nib.load('/home/hdd2/jo/nnUNet_raw/Dataset218_AMOS2022_postChallenge_task1/imagesTr/amos_0001_0000.nii.gz')
data = img.get_fdata()  # numpy array of image voxel data
print(data.shape)
print("Shape:", data.shape)
print("Data type:", data.dtype)
print("Intensity range:", data.min(), "to", data.max())

(768, 768, 90)
Shape: (768, 768, 90)
Data type: float64
Intensity range: -1024.0 to 1373.0


In [25]:
import nibabel as nib

img = nib.load('/home/hdd2/jo/nnUNet_preprocessed/Dataset218_AMOS2022_postChallenge_task1/gt_segmentations/amos_0408.nii.gz')
data = img.get_fdata()  # numpy array of image voxel data
print(data.shape)
print("Shape:", data.shape)
print("Data type:", data.dtype)
print("Intensity range:", data.min(), "to", data.max())

(768, 768, 104)
Shape: (768, 768, 104)
Data type: float64
Intensity range: 0.0 to 15.0


In [ ]:
import numpy as np
import os

label_path = "/home/hdd2/jo/nnUNet_preprocessed/Dataset218_AMOS2022_postChallenge_task1/nnUNetPlans_3d_fullres/amos_0408.npz"
total_neg_voxels = 0
with np.load(label_path) as data:
    data_dict = dict(data)  # now writable
    label = data_dict['seg']

# Check and patch label
if np.any(label < 0):
    print("Before patching:", label.min(), label.shape, label.max())
    neg_count = np.sum(label == -1)
    label[label < 0] = 0
    print("After patching:", label.min())
    data_dict['seg'] = label
    print(neg_count)

    # Save back
    # np.savez(label_path, **data_dict)
    print(f"Patched and saved: {label_path}")
else:
    print("No patching needed.")
    

Before patching: -1 (1, 260, 689, 689)
After patching: 0
875
Patched and saved: /home/hdd2/jo/nnUNet_preprocessed/Dataset218_AMOS2022_postChallenge_task1/nnUNetPlans_3d_fullres/amos_0408.npz


In [ ]:
import nibabel as nib

# Load the .nii or .nii.gz file
img = nib.load("/home/hdd2/jo/amos22/imagesTs/amos_0002.nii.gz")

# Get the image data as a NumPy array
data = img.get_fdata()

# Print the shape
print("Shape:", data)

Shape: (512, 512, 90)


In [ ]:
import json
import os
import re

def strip_extension(filename):
    # Remove both .nii and .gz extensions
    base = os.path.basename(filename)
    if base.endswith(".nii.gz"):
        return base.replace(".nii.gz", "")
    return os.path.splitext(base)[0]

def filter_by_id_limit(id_list, max_id=500):
    filtered = []
    for item in id_list:
        match = re.search(r'AMOS_(\d+)', item)
        if match and int(match.group(1)) <= max_id:
            filtered.append(item)
    return filtered

# Load the original JSON
with open("/home/jovianto/amos22/dataset.json", "r") as f:
    data = json.load(f)

# Extract and filter IDs
train_ids = [strip_extension(item["image"]) for item in data.get("training", [])]
val_ids = [strip_extension(item["image"]) for item in data.get("validation", [])]

train_ids = filter_by_id_limit(train_ids, 500)
val_ids = filter_by_id_limit(val_ids, 500)

# Format output
output_data = [{"train": train_ids, "val": val_ids}]

# Save to new JSON
with open("/home/jovianto/nnUNet_preprocessed/Dataset218_AMOS2022_postChallenge_task1/split.json", "w") as f:
    json.dump(output_data, f, indent=2)
